# Generated by Django 4.1.4 on 2023-01-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapiapp', '0013_remove_myteam_id_remove_myteammember_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myteam',
            name='team_id',
        ),
        migrations.RemoveField(
            model_name='myteammember',
            name='team_member_id',
        ),
        migrations.AddField(
            model_name='myteam',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myteammember',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myproject',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
