# Generated by Django 4.1.4 on 2023-01-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapiapp', '0010_alter_myteammember_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproject',
            name='proj_id',
            field=models.AutoField(db_column='proj_id', primary_key=True, serialize=False),
        ),
        migrations.RenameField(
            model_name='myproject',
            old_name='proj_id',
            new_name='id',
        ),
    ]
