# Generated by Django 4.1.4 on 2023-01-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapiapp', '0012_alter_myteam_team_id_rename_team_id_myteam_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myteam',
            name='id',
        ),
        migrations.RemoveField(
            model_name='myteammember',
            name='id',
        ),
        migrations.AddField(
            model_name='myteam',
            name='team_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myteammember',
            name='team_member_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
